# Generated by Django 4.1 on 2023-08-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='examiner',
            field=models.CharField(choices=[('', ''), ('admin', 'admin'), ('mayowa', 'mayowa')], default=('', ''), max_length=100),
        ),
    ]
