# Generated by Django 4.1 on 2023-08-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_question_examiner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='examiner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
