# Generated by Django 4.1 on 2023-08-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0005_alter_exam_description_alter_question_op1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='op1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='op2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='op3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='op4',
            field=models.TextField(),
        ),
    ]
